import type {
  DocumentProps,
} from "@react-pdf/renderer";

import {
  Document,
  Page,
  Text,
  View,
} from "@react-pdf/renderer";

import type {
  ReactElement,
} from "react";

import { pdfTheme } from "@/lib/pdf/pdfTheme";

type Props = {
  report: {
    property_address?: string | null;
    investor_type?: string | null;
    created_at?: string | null;
    is_full_report?: boolean | null;
    report_html?: string | null;
  };

  property?: any;
};

function money(value?: number | null) {
  if (
    value === null ||
    value === undefined ||
    !Number.isFinite(Number(value))
  ) {
    return "—";
  }

  return `$${Math.round(
    Number(value),
  ).toLocaleString("en-US")}`;
}

export default function PropertyReportPdf({
  report,
  property,
}: Props): ReactElement<DocumentProps> {
  const address =
    property?.address ||
    report.property_address ||
    "Property";

  const score =
    Number(
      property?.overall_score ??
        property?.deal_score ??
        0,
    );

  const listingPrice =
    Number(property?.listing_price ?? 0);

  const fairValue =
    Number(property?.fair_value ?? 0);

  const rent =
    Number(
      property?.estimated_monthly_rent ?? 0,
    );

  const cashFlow =
    Number(
      property?.estimated_monthly_cash_flow ??
        0,
    );

  const yieldValue =
    Number(property?.gross_rent_yield ?? 0);

  const appreciation =
    Number(
      property?.expected_appreciation ?? 0,
    );

  const confidence =
    Number(property?.confidence_score ?? 0);

  const negotiation =
    property?.negotiation ?? {};

  const comparables =
    property?.comparables ?? [];

  return (
    <Document>
      <Page size="A4" style={pdfTheme.page}>
        <Text style={pdfTheme.title}>
          Nestrova Property Intelligence
        </Text>

        <Text style={pdfTheme.subtitle}>
          {address}
        </Text>

        <View style={pdfTheme.section}>
          <Text style={pdfTheme.sectionTitle}>
            Executive Summary
          </Text>

          <View style={pdfTheme.card}>
            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                Investment Score
              </Text>

              <Text style={pdfTheme.value}>
                {score}/100
              </Text>
            </View>

            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                Listing Price
              </Text>

              <Text style={pdfTheme.value}>
                {money(listingPrice)}
              </Text>
            </View>

            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                AI Fair Value
              </Text>

              <Text style={pdfTheme.value}>
                {money(fairValue)}
              </Text>
            </View>

            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                AI Confidence
              </Text>

              <Text style={pdfTheme.value}>
                {confidence}%
              </Text>
            </View>
          </View>
        </View>

        <View style={pdfTheme.section}>
          <Text style={pdfTheme.sectionTitle}>
            Rental & Cash Flow
          </Text>

          <View style={pdfTheme.card}>
            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                Estimated Monthly Rent
              </Text>

              <Text style={pdfTheme.value}>
                {money(rent)}
              </Text>
            </View>

            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                Monthly Cash Flow
              </Text>

              <Text style={pdfTheme.value}>
                {money(cashFlow)}
              </Text>
            </View>

            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                Gross Rental Yield
              </Text>

              <Text style={pdfTheme.value}>
                {yieldValue.toFixed(2)}%
              </Text>
            </View>

            <View style={pdfTheme.row}>
              <Text style={pdfTheme.label}>
                Expected Appreciation
              </Text>

              <Text style={pdfTheme.value}>
                {appreciation.toFixed(1)}%
              </Text>
            </View>
          </View>
        </View>

        <Text style={pdfTheme.footer}>
          Generated by Nestrova AI
        </Text>
      </Page>

      <Page size="A4" style={pdfTheme.page}>
        <Text style={pdfTheme.sectionTitle}>
          Negotiation AI
        </Text>

        <View style={pdfTheme.card}>
          <View style={pdfTheme.row}>
            <Text style={pdfTheme.label}>
              Opening Offer
            </Text>

            <Text style={pdfTheme.value}>
              {money(
                negotiation.suggested_offer,
              )}
            </Text>
          </View>

          <View style={pdfTheme.row}>
            <Text style={pdfTheme.label}>
              Recommended Target
            </Text>

            <Text style={pdfTheme.value}>
              {money(
                negotiation.recommended_target,
              )}
            </Text>
          </View>

          <View style={pdfTheme.row}>
            <Text style={pdfTheme.label}>
              Walk-Away Price
            </Text>

            <Text style={pdfTheme.value}>
              {money(
                negotiation.walk_away_price,
              )}
            </Text>
          </View>

          <View style={pdfTheme.row}>
            <Text style={pdfTheme.label}>
              Comparable Median
            </Text>

            <Text style={pdfTheme.value}>
              {money(
                negotiation.comparable_median,
              )}
            </Text>
          </View>
        </View>

        <Text style={pdfTheme.sectionTitle}>
          Comparable Intelligence
        </Text>

        {comparables.slice(0, 5).map(
          (comp: any, index: number) => (
            <View
              key={
                comp.id ??
                `${comp.address}-${index}`
              }
              style={pdfTheme.card}
            >
              <View style={pdfTheme.row}>
                <Text style={pdfTheme.label}>
                  Address
                </Text>

                <Text style={pdfTheme.value}>
                  {comp.address ?? "—"}
                </Text>
              </View>

              <View style={pdfTheme.row}>
                <Text style={pdfTheme.label}>
                  Price
                </Text>

                <Text style={pdfTheme.value}>
                  {money(comp.price)}
                </Text>
              </View>

              <View style={pdfTheme.row}>
                <Text style={pdfTheme.label}>
                  Similarity
                </Text>

                <Text style={pdfTheme.value}>
                  {Math.round(
                    Number(
                      comp.similarity_score ??
                        0,
                    ),
                  )}
                  /100
                </Text>
              </View>
            </View>
          ),
        )}

        <Text style={pdfTheme.footer}>
          This report is informational only and
          is not financial, legal, tax, or
          investment advice.
        </Text>
      </Page>
    </Document>
  );
}
