import type { CompareProperty } from "@/types/comparison";

export const mockCompareProperties: CompareProperty[] = [
  {
    id: "irvine-157-damsel",
    address: "157 Damsel",
    city: "Irvine",
    state: "CA",
    price: 1490000,
    fairValue: 1583000,
    estimatedRent: 4680,
    brainScore: 92,
    riskScore: 84,
    rentalScore: 76,
    negotiationScore: 89,
    forecastScore: 86,
    cashflowScore: 72,
    roiScore: 88,
    recommendation: "BUY",
    summary: "Strong value spread with controlled risk and above-average negotiation leverage.",
    strengths: ["Highest brain score", "Positive value spread", "Strong negotiation setup"],
    risks: ["California carrying costs", "Rent yield should be verified", "Insurance assumptions need review"],
  },
  {
    id: "austin-221-lakeview",
    address: "221 Lakeview",
    city: "Austin",
    state: "TX",
    price: 785000,
    fairValue: 820000,
    estimatedRent: 3950,
    brainScore: 87,
    riskScore: 79,
    rentalScore: 91,
    negotiationScore: 75,
    forecastScore: 82,
    cashflowScore: 86,
    roiScore: 84,
    recommendation: "NEGOTIATE",
    summary: "Excellent rental profile, but offer discipline is needed before committing.",
    strengths: ["Best rental score", "Good cashflow profile", "Lower entry price"],
    risks: ["Market volatility", "Property tax burden", "Moderate negotiation leverage"],
  },
  {
    id: "phoenix-88-desert",
    address: "88 Desert Ridge",
    city: "Phoenix",
    state: "AZ",
    price: 642000,
    fairValue: 650000,
    estimatedRent: 2850,
    brainScore: 74,
    riskScore: 68,
    rentalScore: 72,
    negotiationScore: 66,
    forecastScore: 76,
    cashflowScore: 70,
    roiScore: 71,
    recommendation: "WAIT",
    summary: "Acceptable but not exceptional. Better entry price or stronger rent support is needed.",
    strengths: ["Lower absolute price", "Moderate forecast score", "Potential price flexibility"],
    risks: ["Thin value spread", "Moderate risk score", "Weaker negotiation profile"],
  },
];
