"use client";

import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type ReportItem = {
  id: string;
  property_address: string;
  investor_type: string;
  is_full_report: boolean;
  created_at: string;
};

export default function ReportsPage() {
  const [signedIn, setSignedIn] = useState(false);
  const [reports, setReports] = useState<ReportItem[]>([]);
  const [message, setMessage] = useState("");

  useEffect(() => {
    async function init() {
      const supabase = createSupabaseBrowserClient();
      const { data } = await supabase.auth.getUser();
      setSignedIn(Boolean(data.user));
      if (data.user) loadReports();
    }
    init();
  }, []);

  async function loadReports() {
    const response = await fetch("/api/reports", { cache: "no-store" });
    const data = await response.json();
    if (!response.ok) return setMessage(data.error || "Could not load reports.");
    setReports(data.reports || []);
  }

  async function deleteReport(id: string) {
    const response = await fetch(`/api/reports?id=${encodeURIComponent(id)}`, { method: "DELETE" });
    const data = await response.json();
    if (!response.ok) return setMessage(data.error || "Could not delete report.");
    setReports((prev) => prev.filter((report) => report.id !== id));
  }

  if (!signedIn) {
    return (
      <main className="min-h-screen bg-[#050505] p-8 text-white">
        <div className="mx-auto max-w-xl rounded-[40px] border border-white/10 bg-white/[0.07] p-8">
          <h1 className="text-5xl font-semibold tracking-[-0.06em]">Saved Reports</h1>
          <p className="mt-4 text-white/55">Sign in to view your saved AI reports.</p>
          <a href="/login" className="mt-6 inline-block rounded-full bg-white px-6 py-3 text-sm font-semibold text-black">Sign In</a>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#050505] p-8 text-white">
      <div className="mx-auto max-w-6xl">
        <div className="flex items-center justify-between">
          <a href="/dashboard" className="text-sm font-semibold text-white/50 hover:text-white">??Dashboard</a>
          <a href="/analyze" className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-black">Create Report</a>
        </div>
        <h1 className="mt-8 text-6xl font-semibold tracking-[-0.07em]">Saved Reports</h1>
        <p className="mt-4 text-white/55">All AI investment reports generated by your account.</p>
        {message && <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.07] p-4 text-white/70">{message}</div>}
        <section className="mt-8 grid gap-4">
          {reports.length === 0 && <div className="rounded-3xl border border-white/10 bg-white/[0.06] p-8 text-white/55">No reports yet.</div>}
          {reports.map((report) => (
            <div key={report.id} className="rounded-3xl border border-white/10 bg-white/[0.06] p-6">
              <p className="text-xs font-semibold uppercase tracking-[0.22em] text-white/35">{report.is_full_report ? "Full Pro Report" : "Preview Report"}</p>
              <h2 className="mt-2 text-2xl font-semibold">{report.property_address || "Investment report"}</h2>
              <p className="mt-2 text-sm text-white/45">{new Date(report.created_at).toLocaleString()}</p>
              <div className="mt-5 flex flex-wrap gap-3">
                <a href={`/report/${report.id}`} className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-black">Open Report</a>
                <button onClick={() => deleteReport(report.id)} className="rounded-full border border-white/10 bg-white/[0.06] px-5 py-3 text-sm font-semibold text-white/65">Delete</button>
              </div>
            </div>
          ))}
        </section>
      </div>
    </main>
  );
}

